spring:
  datasource:
    url: jdbc:postgresql://db:5432/library
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    org.springframework: WARN

library:
  max-penalty-points: 10
  max-user-rentals: 3
  rental-period-days: 14
  allow-rental-extension: true
  enable-notifications: true
  reminder-days: 2
  overdue-check-interval: 24
