spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://db:5432//${POSTGRES_DB}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /api/

library:
  max-penalty-points: 10
  max-user-rentals: 3
  overdue-penalty: 2
  late-overdue-penalty: 5
  rental-period-days: 14
  allow-rental-extension: true
  enable-notifications: true
  reminder-days: 2
  overdue-check-interval: 24
