#version: '3.8'
#
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - SPRING_PROFILES_ACTIVE=dev
#
#  db:
#    image: postgres:14
#    ports:
#      - "5433:5432"
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
#      - POSTGRES_DB=library
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#        test: [ "CMD-SHELL", "pg_isready -U admin" ]
#        interval: 10s
#        timeout: 5s
#        retries: 5
#
#
#volumes:
#  postgres_data:

version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=prod

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: library-postgres-data