spring:
  datasource:
    url: jdbc:postgresql://db:5432/library
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

logging:
  level:
    org.springframework: WARN